version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  # Python
  - package-ecosystem: "pip"
    directory: "back"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  # Npm
  - package-ecosystem: "npm"
    directory: "front"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
