name: Api

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/api/**'
      - 'backend/core/**'
      - 'backend/docker/api.Dockerfile'
      - 'kubernetes/api-**.yaml'
      - '.github/workflows/api.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: rg.fr-par.scw.cloud/atom-namespace
    - name: Build the Docker image
      run: docker build . -f ./backend/docker/api.Dockerfile -t rg.fr-par.scw.cloud/atom-namespace/apps/scan-api
    - name: Push the Docker Image
      run: docker push rg.fr-par.scw.cloud/atom-namespace/apps/scan-api

  deploy:
    needs: [build]
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'nginx'
        track: canary
        namespace: 'default'
        chart: 'app'
        token: '${{ github.token }}'
        values: |
          name: foobar
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
