name: Api

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/api/**'
      - 'backend/core/**'
      - 'backend/docker/api.Dockerfile'
      - 'kubernetes/api-**.yaml'
      - '.github/workflows/api.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: rg.fr-par.scw.cloud/atom-namespace
    - name: Build the Docker image
      run: docker build . -f ./backend/docker/api.Dockerfile -t rg.fr-par.scw.cloud/atom-namespace/apps/scan-api
    - name: Push the Docker Image
      run: docker push rg.fr-par.scw.cloud/atom-namespace/apps/scan-api

#  deploy:
#    needs: [build]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set the Kubernetes context
#        uses: azure/k8s-set-context@v2
#        with:
#          method: service-account
#          k8s-url: <server-url>
#          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
#
#      - name: Checkout source code
#        uses: actions/checkout@v3
#
#      - name: Deploy to the Kubernetes cluster
#        uses: azure/k8s-deploy@v1
#        with:
#          namespace: default
#          manifests: |
#            kubernetes/api-deployment.yaml
#            kubernetes/api-ingress.yaml
#            kubernetes/api-service.yaml
#          images: |
#            ghcr.io/username/package:${{ github.sha }}
#
