name: Build & Deploy to Scaleway

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/docker/beat.Dockerfile'
      - 'kubernetes/beat-**.yaml'
      - '.github/workflows/beat.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: rg.fr-par.scw.cloud/atom-namespace
    - name: Build the Docker image
      run: docker build . -f ./backend/docker/beat.Dockerfile -t rg.fr-par.scw.cloud/atom-namespace/apps/scan-beat
    - name: Push the Docker Image
      run: docker push rg.fr-par.scw.cloud/atom-namespace/apps/scan-beat
