name: Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'frontend/**'
      - 'kubernetes/frontend-**.yaml'
      - '.github/workflows/frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: rg.fr-par.scw.cloud/atom-namespace
    - name: Build the Docker image
      run: docker build . -f ./frontend/Dockerfile -t rg.fr-par.scw.cloud/atom-namespace/apps/scan-frontend
    - name: Push the Docker Image
      run: docker push rg.fr-par.scw.cloud/atom-namespace/apps/scan-frontend
